import { useEffect } from 'react';
import { ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';

const sections = [
  ['Interpretation and definitions', 'Aayiram is the mobile software application provided by the Company. “Personal Data” means information relating to an identified or identifiable individual. “Usage Data” means information collected automatically, including device information, IP address, and usage patterns. “Service Provider” means a third party that helps us provide the Application.'],
  ['Usage data', 'Usage Data may include your device IP address, device type, operating system and version, pages visited, time and date of visits, time spent in the Application, unique device identifiers, and diagnostic data.'],
  ['How we use personal data', 'We use information to provide and maintain Aayiram, monitor usage and performance, identify trends and improve the user experience, provide customer support, and meet legal or regulatory obligations.'],
  ['Advertising — Google AdMob', 'Aayiram displays advertisements served by Google AdMob, an advertising platform operated by Google LLC. AdMob may collect device and advertising identifiers, IP address, cookies or similar technologies, ad interactions, device information, and approximate location based on IP address. Google may use this data to serve personalized or non-personalized ads, measure performance, prevent fraud, and improve its advertising services.'],
  ['Your advertising choices', 'You can manage personalized advertising through Google Ads Settings or your device-level ad-personalization controls. On Android, go to Settings → Google → Manage your Google Account → Data & Privacy → Ad personalization. You will still see ads after opting out, but they may not be personalized.'],
  ['Retention and security', 'We retain Personal Data only for as long as necessary for the purposes in this policy and to comply with legal obligations. Usage Data is generally retained for internal analysis for a shorter period, unless needed for security or improved functionality. No transmission method is 100% secure, but we use commercially reasonable safeguards to protect your information.'],
  ['Children and external links', 'Aayiram is not intended for individuals under 13. We do not knowingly collect personally identifiable information from children under 13. The Application may link to third-party websites or services; their privacy practices are governed by their own policies.'],
  ['Changes and contact', 'We may update this policy and will publish the latest version here with an updated date. If you have questions, contact redgoldcrew@gmail.com. Location: Tamil Nadu, India.'],
];

export default function AayiramPrivacyPage() {
  useEffect(() => { document.title = 'Aayiram — Privacy Policy'; }, []);
  return <div className="min-h-screen bg-[#07111f] text-white"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_15%_0%,rgba(196,28,28,.24),transparent_32%),radial-gradient(circle_at_90%_22%,rgba(212,160,23,.18),transparent_27%)]" />
    <header className="relative z-10 border-b border-white/10 bg-[#07111f]/85 backdrop-blur-xl"><div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4"><Link to="/aayiram" className="font-rajdhani text-sm font-bold uppercase tracking-[.2em] text-slate-200 hover:text-white"><span className="text-gold-primary">←</span> Aayiram</Link><Link to="/" className="font-rajdhani text-sm font-bold uppercase tracking-[.16em] text-gold-primary hover:text-white">RedGoldCrew</Link></div></header>
    <main className="relative z-10 mx-auto max-w-5xl px-6 py-16 lg:py-24"><article className="rounded-2xl border border-gold-primary/30 bg-[#0b1727]/90 p-8 shadow-2xl shadow-black/30 sm:p-12"><div className="flex items-center gap-3 text-gold-primary"><ShieldCheck className="h-7 w-7" /><span className="font-rajdhani text-sm font-bold uppercase tracking-[.2em]">Aayiram legal</span></div><h1 className="mt-6 font-bebas text-5xl leading-none sm:text-6xl">PRIVACY POLICY</h1><p className="mt-4 font-nunito text-lg text-slate-300">For the Aayiram Mobile Application</p><p className="mt-3 font-nunito text-sm text-slate-500">Last updated: January 9, 2026</p><p className="mt-8 font-nunito leading-8 text-slate-300">This Privacy Policy describes how Aayiram collects, uses, and discloses information when you use the Application and related services. By using Aayiram, you agree to the collection and use of information described here.</p><div className="mt-10 space-y-8">{sections.map(([heading, body]) => <section key={heading}><h2 className="font-rajdhani text-2xl font-bold uppercase text-gold-primary">{heading}</h2><p className="mt-3 font-nunito leading-8 text-slate-300">{body}</p></section>)}</div><section className="mt-8"><h2 className="font-rajdhani text-2xl font-bold uppercase text-gold-primary">Google resources</h2><div className="mt-3 flex flex-wrap gap-4 font-nunito text-sm"><a className="text-gold-primary hover:text-white" href="https://adssettings.google.com/" target="_blank" rel="noreferrer">Google Ads Settings ↗</a><a className="text-gold-primary hover:text-white" href="https://policies.google.com/privacy" target="_blank" rel="noreferrer">Google Privacy Policy ↗</a><a className="text-gold-primary hover:text-white" href="https://support.google.com/admob/" target="_blank" rel="noreferrer">AdMob Help Center ↗</a></div></section><div className="mt-12 border-t border-white/10 pt-8"><Link to="/aayiram/terms" className="font-rajdhani font-bold uppercase tracking-wider text-gold-primary hover:text-white">Terms of Use</Link></div></article></main>
  </div>;
}
