import { useEffect } from 'react';
import { BellRing, CalendarDays, CheckCircle2, Sparkles, TrendingUp } from 'lucide-react';
import { Link } from 'react-router-dom';
import indruLogo from '../assets/Indrulogo.png';

const features = [
  { title: 'Plan every horizon', text: 'Bring daily tasks, weekly priorities, and monthly goals into one clear view.', icon: CalendarDays },
  { title: 'Make tasks actionable', text: 'Set priorities, stay on top of the next step, and see progress without the clutter.', icon: CheckCircle2 },
  { title: 'Build routines that last', text: 'Create habits, track your streaks, and make consistency feel achievable.', icon: TrendingUp },
  { title: 'Stay on time', text: 'Gentle reminders keep important plans from slipping through the day.', icon: BellRing },
];

export default function IndruHomePage() {
  useEffect(() => { document.title = 'Indru — Calm daily planner by RedGoldCrew'; }, []);

  return (
    <div className="min-h-screen overflow-x-hidden bg-[#07111f] text-white">
      <div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_15%_0%,rgba(196,28,28,.24),transparent_32%),radial-gradient(circle_at_90%_22%,rgba(212,160,23,.18),transparent_27%)]" />
      <header className="sticky top-0 z-20 border-b border-white/10 bg-[#07111f]/85 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 lg:px-8"><Link to="/" className="flex items-center gap-3 font-rajdhani text-sm font-bold uppercase tracking-[.2em] text-slate-200 hover:text-white"><span className="text-gold-primary">←</span> RedGoldCrew</Link><Link to="/indru" className="flex items-center gap-2 font-rajdhani text-lg font-bold uppercase tracking-[.14em]"><img src={indruLogo} alt="Indru logo" className="h-10 w-10 rounded-xl border border-white/10 bg-white/10 object-contain p-1" />Indru</Link></div></header>
      <main className="relative z-10">
        <section className="mx-auto grid max-w-7xl gap-12 px-6 pb-24 pt-16 lg:grid-cols-[1.1fr_.9fr] lg:items-center lg:px-8 lg:pt-24">
          <div><div className="inline-flex items-center gap-2 rounded-full border border-gold-primary/40 bg-gold-primary/10 px-4 py-2 font-rajdhani text-sm font-bold uppercase tracking-wider text-gold-primary"><span className="h-2 w-2 animate-pulse rounded-full bg-green-400" /> Android daily planner</div><h1 className="mt-7 font-bebas text-6xl leading-[.88] sm:text-8xl">PLAN YOUR DAY.<br /><span className="bg-gradient-to-r from-red-primary to-gold-primary bg-clip-text text-transparent">LIVE CLEARLY.</span></h1><p className="mt-6 max-w-xl font-nunito text-lg leading-8 text-slate-300">Indru is a calm daily planner for organizing what matters, building better routines, and seeing your progress — one focused day at a time.</p><div className="mt-8 flex flex-wrap gap-4"><a href="#features" className="rounded bg-red-primary px-7 py-3.5 font-rajdhani font-bold uppercase tracking-wider shadow-[0_0_24px_rgba(196,28,28,.45)] transition hover:bg-red-500">Explore features</a><a href="#how-it-works" className="rounded border border-gold-primary px-7 py-3.5 font-rajdhani font-bold uppercase tracking-wider text-gold-primary transition hover:bg-gold-primary hover:text-[#07111f]">How it works</a></div></div>
          <div className="relative mx-auto w-full max-w-sm"><div className="absolute inset-8 rounded-full bg-gold-primary/20 blur-3xl" /><div className="relative rounded-[2.6rem] border-4 border-slate-700 bg-[#111d2d] p-2 shadow-2xl shadow-black/60"><div className="overflow-hidden rounded-[2rem] bg-gradient-to-b from-[#1c3048] to-[#0c1625] p-5"><div className="mx-auto mb-6 h-5 w-24 rounded-b-xl bg-[#111d2d]" /><div className="flex items-center gap-3"><img src={indruLogo} alt="" className="h-10 w-10 rounded-xl object-contain" /><div><p className="font-rajdhani text-xs uppercase tracking-widest text-slate-400">Today</p><p className="font-rajdhani text-2xl font-bold">A clear day ahead</p></div></div><div className="mt-6 rounded-2xl border border-white/10 bg-white/10 p-4"><p className="font-rajdhani text-sm text-gold-primary">4 TASKS AHEAD</p><p className="mt-1 font-nunito text-sm text-slate-300">Start with what matters most.</p></div><div className="mt-4 space-y-3">{['Morning routine', 'Client follow-up', 'Workout reset'].map((task, index) => <div key={task} className="flex items-center gap-3 rounded-xl bg-white/8 px-3 py-3"><span className={`h-2.5 w-2.5 rounded-full ${index === 0 ? 'bg-gold-primary' : 'bg-red-primary'}`} /><span className="font-nunito text-sm text-slate-200">{task}</span></div>)}</div><div className="mt-4 flex items-center gap-2 rounded-2xl bg-green-500/10 p-3 text-sm text-slate-200"><TrendingUp className="h-5 text-green-400" /> 7-day routine streak.</div></div></div></div>
        </section>
        <section className="border-y border-white/10 bg-[#0b1727]/80 py-8"><div className="mx-auto grid max-w-6xl grid-cols-1 gap-6 px-6 text-center sm:grid-cols-3 lg:px-8">{[['One calm space', 'For tasks, habits, and plans'], ['Clear progress', 'See what you completed'], ['Android app', 'Built for everyday focus']].map(([title, text]) => <div key={title}><p className="font-rajdhani text-xl font-bold uppercase text-gold-primary">{title}</p><p className="mt-1 font-nunito text-sm text-slate-400">{text}</p></div>)}</div></section>
        <section id="features" className="mx-auto max-w-7xl px-6 py-24 lg:px-8"><p className="font-rajdhani font-bold uppercase tracking-[.22em] text-red-primary">Everything you need, nothing you don’t</p><h2 className="mt-3 font-bebas text-5xl leading-none sm:text-6xl">CALM PLANNING.<br /><span className="text-gold-primary">REAL PROGRESS.</span></h2><div className="mt-12 grid gap-5 md:grid-cols-2">{features.map(({ title, text, icon: Icon }) => <article key={title} className="rounded-2xl border border-white/10 bg-white/5 p-7 transition hover:border-gold-primary/60 hover:bg-white/[.07]"><Icon className="h-9 w-9 text-gold-primary" /><h3 className="mt-5 font-rajdhani text-2xl font-bold uppercase">{title}</h3><p className="mt-3 font-nunito leading-7 text-slate-300">{text}</p></article>)}</div></section>
        <section id="how-it-works" className="border-y border-white/10 bg-[#0b1727]/70 px-6 py-24 lg:px-8"><div className="mx-auto max-w-7xl"><p className="font-rajdhani font-bold uppercase tracking-[.22em] text-red-primary">Simple from the start</p><h2 className="mt-3 font-bebas text-5xl sm:text-6xl">HOW INDRU WORKS</h2><div className="mt-12 grid gap-6 md:grid-cols-3">{[['Plan your day', 'Add tasks, set priorities, and organize a day that feels manageable.'], ['Build your rhythm', 'Create routines that support your goals and keep your momentum going.'], ['See your growth', 'Track completed tasks and streaks to understand your progress over time.']].map(([title, text], index) => <article key={title} className="rounded-2xl border border-white/10 bg-[#07111f] p-7"><span className="font-bebas text-6xl text-red-primary/50">0{index + 1}</span><h3 className="mt-4 font-rajdhani text-2xl font-bold uppercase text-gold-primary">{title}</h3><p className="mt-3 font-nunito leading-7 text-slate-300">{text}</p></article>)}</div></div></section>
        <section className="mx-auto max-w-4xl px-6 py-24 text-center lg:px-8"><Sparkles className="mx-auto h-10 w-10 text-gold-primary" /><h2 className="mt-5 font-bebas text-5xl leading-none sm:text-6xl">PLAN BETTER.<br /><span className="text-gold-primary">LIVE CLEARER.</span></h2><p className="mx-auto mt-5 max-w-2xl font-nunito text-lg leading-8 text-slate-300">Indru gives your day a little more clarity, without turning planning into another job.</p><div className="mt-8 flex flex-wrap justify-center gap-4"><Link to="/indru/privacy" className="rounded border border-gold-primary px-7 py-3.5 font-rajdhani font-bold uppercase tracking-wider text-gold-primary transition hover:bg-gold-primary hover:text-[#07111f]">Privacy policy</Link><Link to="/indru/terms" className="rounded border border-white/20 px-7 py-3.5 font-rajdhani font-bold uppercase tracking-wider text-white transition hover:border-white">Terms of use</Link></div></section>
      </main>
      <footer className="relative z-10 border-t border-white/10 px-6 py-8 text-center font-nunito text-sm text-slate-400">Indru by <Link to="/" className="text-gold-primary hover:text-white">RedGoldCrew</Link> · Plan your day. Live clearly.</footer>
    </div>
  );
}
