import { useEffect } from 'react';
import { CheckCircle2, ShieldAlert, Trash2 } from 'lucide-react';
import { Link } from 'react-router-dom';

const deletedData = ['User profile, name, email address, and profile picture', 'Firebase Authentication account', 'Trips created by you, trip expenses, tasks, and membership information', 'Preferences, settings, app-generated personal data, and associated metadata'];

export default function UllaDeletionPage() {
  useEffect(() => { document.title = 'Ulla — Account & Data Deletion'; }, []);
  return <div className="min-h-screen bg-[#07111f] text-white"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_15%_0%,rgba(196,28,28,.24),transparent_32%),radial-gradient(circle_at_90%_22%,rgba(212,160,23,.18),transparent_27%)]" />
    <header className="relative z-10 border-b border-white/10 bg-[#07111f]/85 backdrop-blur-xl"><div className="mx-auto flex max-w-5xl items-center justify-between px-6 py-4"><Link to="/ulla" className="font-rajdhani text-sm font-bold uppercase tracking-[.2em] text-slate-200 hover:text-white"><span className="text-gold-primary">←</span> Ulla</Link><Link to="/" className="font-rajdhani text-sm font-bold uppercase tracking-[.16em] text-gold-primary hover:text-white">RedGoldCrew</Link></div></header>
    <main className="relative z-10 mx-auto max-w-5xl px-6 py-16 lg:py-24"><article className="rounded-2xl border border-red-primary/40 bg-[#0b1727]/90 p-8 shadow-2xl shadow-black/30 sm:p-12"><div className="flex items-center gap-3 text-red-300"><Trash2 className="h-7 w-7" /><span className="font-rajdhani text-sm font-bold uppercase tracking-[.2em]">Ulla account & data deletion</span></div><h1 className="mt-6 font-bebas text-5xl leading-none sm:text-6xl">DELETE YOUR<br /><span className="text-gold-primary">ULLA ACCOUNT</span></h1><p className="mt-5 font-nunito leading-8 text-slate-300">This official page explains how Ulla users can permanently delete their account and associated personal data.</p><div className="mt-8 grid gap-4 rounded-xl border border-white/10 bg-white/5 p-5 font-nunito text-slate-300 sm:grid-cols-3"><p><strong className="block text-gold-primary">App name</strong>Ulla</p><p><strong className="block text-gold-primary">Package name</strong>com.manikandan.tripoo</p><p><strong className="block text-gold-primary">Developer</strong>Red Gold Crew</p></div>
      <section className="mt-10"><h2 className="font-rajdhani text-2xl font-bold uppercase text-gold-primary">How to request deletion</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><div className="rounded-xl border border-gold-primary/30 bg-[#07111f] p-6"><p className="font-rajdhani text-xl font-bold uppercase">1. From the app <span className="text-gold-primary">(recommended)</span></p><ol className="mt-4 list-decimal space-y-2 pl-5 font-nunito text-slate-300"><li>Open Ulla and sign in.</li><li>Go to Profile → Settings → Delete Account.</li><li>Confirm your deletion request.</li></ol><p className="mt-4 font-nunito text-sm text-slate-400">This is the fastest and most secure method.</p></div><div className="rounded-xl border border-white/10 bg-[#07111f] p-6"><p className="font-rajdhani text-xl font-bold uppercase">2. By email</p><p className="mt-4 font-nunito text-slate-300">If you cannot access your account, email <a href="mailto:support@ulla.app?subject=Ulla%20Account%20Deletion%20Request" className="text-gold-primary hover:text-white">support@ulla.app</a> with the subject <strong>Ulla Account Deletion Request</strong>.</p><p className="mt-3 font-nunito text-slate-300">Include your registered email address and a request to permanently delete your account. We may verify account ownership before processing.</p></div></div></section>
      <section className="mt-10"><h2 className="font-rajdhani text-2xl font-bold uppercase text-gold-primary">What happens after your request</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{['We verify account ownership.', 'Your account and personal information are permanently deleted from production systems.', 'You lose access to the account. This cannot be reversed.', 'Requests are normally completed within 7 days.'].map(item => <p key={item} className="flex gap-3 rounded-xl border border-white/10 bg-white/5 p-4 font-nunito text-slate-300"><CheckCircle2 className="h-5 shrink-0 text-green-400" />{item}</p>)}</div></section>
      <section className="mt-10"><h2 className="font-rajdhani text-2xl font-bold uppercase text-gold-primary">Data that will be deleted</h2><ul className="mt-5 space-y-3">{deletedData.map(item => <li key={item} className="flex gap-3 font-nunito text-slate-300"><CheckCircle2 className="h-5 shrink-0 text-green-400" />{item}</li>)}</ul></section>
      <section className="mt-10 rounded-xl border border-red-primary/30 bg-red-primary/10 p-6"><div className="flex gap-3"><ShieldAlert className="h-6 shrink-0 text-red-300" /><div><h2 className="font-rajdhani text-2xl font-bold uppercase text-white">Before you delete</h2><p className="mt-3 font-nunito leading-8 text-slate-200">You will permanently lose access to your account and trips you own. Shared trip information may remain visible to other members where needed to preserve trip history. Deleted accounts cannot be recovered; to use Ulla again, you must create a new account. Download important data before requesting deletion.</p><p className="mt-3 font-nunito leading-8 text-slate-200">Server logs and automated backups may retain information for security, fraud prevention, legal compliance, or backup recovery. Backups are automatically removed within 30 days and are not used for marketing after your deletion request is processed.</p></div></div></section><div className="mt-10 border-t border-white/10 pt-8 font-nunito text-slate-300">Need help? Contact <a href="mailto:support@ulla.app" className="text-gold-primary hover:text-white">support@ulla.app</a><div className="mt-5 flex gap-5"><Link to="/ulla/privacy" className="font-rajdhani font-bold uppercase tracking-wider text-gold-primary hover:text-white">Privacy Policy</Link><Link to="/ulla/terms" className="font-rajdhani font-bold uppercase tracking-wider text-gold-primary hover:text-white">Terms of Service</Link></div></div></article></main>
  </div>;
}
